version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t package

  build:
    commands:
      - echo "Creating deployment package..."
      - cp lambda_function.py package/
      - cd package
      - zip -r ../deployment_package.zip .
      - cd ..
      - echo "Zipping complete!"

  post_build:
    commands:
      - echo "Uploading package to S3..."
      - aws s3 cp deployment_package.zip s3://lambda-builds-zip8081/deployment_package.zip

      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name DoorDash --s3-bucket lambda-builds-zip8081 --s3-key deployment_package.zip

      - echo "Waiting for Lambda deployment..."
      - sleep 10

      - echo "Publishing new version..."
      - VERSION=$(aws lambda publish-version --function-name DoorDash --query Version --output text || echo "FAILED")

      - if [ "$VERSION" = "FAILED" ]; then
          echo "Lambda version publish failed! Skipping alias update.";
        else
          echo "Updating alias to point to new version: $VERSION";
          aws lambda update-alias --function-name DoorDash --name PROD --function-version $VERSION;
        fi

      - echo "Deployment complete!"
